#!/bin/bash

# extend alias (trailing space aliases check next word for alias substitution)
alias man='man '
alias sudo='sudo '

# auto options
alias emacs='emacs -nw'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls --color=auto'
alias nl='nl -ba'
alias pacman='pacman --color=auto'
alias rm="rm -ri"
alias tmux='tmux -2'
alias watch='watch --color'

# sudo
alias s='sudo'
alias se='sudo -E '

# general
alias dtime="date +$DTIME_FORMAT"
alias pu='pushd'
alias po='popd'

# extra
alias neko-pull='git -C ~/royal-neko/ pull'
alias np='neko-pull'

# kubernetes
alias mk='minikube'
alias kc='kubectl'
alias kcga='kubectl get all'
alias kcc='kubectl config'
alias kcw='watch kubectl get all'

# ls
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -Al'

# bookmarks
alias bm='bookmark'
alias lbm='load-bookmarks'

# git
alias gbb='git branch -avv'
alias gfa='git-fetch-all'
alias gll='git log --all --graph --decorate --oneline'
alias gr='git reset HEAD'
alias grr='git reset --hard HEAD'

# dpkg and apt-*
alias agg='apt-get install'
alias acc='apt-cache search'
alias aff='apt-file search'

# pacman
alias pm='pacman'

# systemd
alias sc='systemctl'
alias scu='systemctl --user'

# emacs
alias em='emacsclient --alternate-editor="" -t'
alias emk="emacsclient -e '(kill-emacs)'"
alias elisp='emacs -nw --no-init-file --load'
alias emacs-upgrade='elisp ~/royal-neko/scripts/upgrade-emacs-packages'

# docker
alias dps='docker ps -a'
alias dc='docker-compose'
alias dm='docker-machine'

# media player
alias npv='mpv --geometry=600'

# graveyard

## mobile
#alias mobile-mode='source ~/royal-neko/os/mobile/mobile-mode'
#alias mvim='vim -S ~/royal-neko/os/mobile/vimrc-mobile'
