#!/bin/bash

# Include user "bin" dir
PATH=$PATH:~/bin
PATH=$PATH:~/royal-neko/bin

# Include local binaries
PATH=$PATH:./bin

# set DTIME_FORMAT
DTIME_FORMAT='%Y-%m-%dT%H:%M:%S'

export EDITOR='emacsclient --alternate-editor="" -t'
export PAGER='less'

# default less settings
export LESS='-SRX'

# Include functions
source ~/royal-neko/functions

# Include aliases
source ~/royal-neko/alias

localDir=$HOME"/royal-neko/local/"

localAlias=$localDir'alias'
if [ -f "$localAlias" ]; then
	source "$localAlias"
fi

localCommon=$localDir'commonrc'
if [ -f "$localCommon" ]; then
	source "$localCommon"
fi

# Load Bookmarks
load-bookmarks

# source the nvm file if it exists
if [ -x ~/.nvm/nvm.sh ]; then
	source ~/.nvm/nvm.sh
fi

# Run archey if it exists
if [ -x /usr/bin/archey ]; then
	/usr/bin/archey
fi

if [ "$(uname)" = "Darwin" ]; then
	PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
	PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
	MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
	MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"
else
	# set LS_COLORS
	eval $(dircolors)
fi

# set LESS_TERMCAP for colored man pages, etc.
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;33m'
