#!/bin/bash
drive='/dev/sda'

if [ "$drive" -z ]; then
	echo "Please set \"\$drive\" in this script"
	exit 1
fi

pacman -S grub os-prober
grub-install --target=i386-pc "$drive"
grub-mkconfig -o /boot/grub/grub.cfg
