#!/bin/bash

# Before install:
# * Create partition
#	ex. fdisk /dev/sda
# * Format partition
# 	ex. mkfs.ext4 /dev/sda1

# After install
# * Install grub
# * Setup networking
#	ex. ip link
#	    sudo systemctl enable dhcpcd@interface

lsblk
read -p "Enter parition device: " part
read -p "Enter swap partition: " swapPart
read -p "Enter hostname: " hostname

mount "$part" /mnt
swapon "$swapPart"

# Install base
pacstrap /mnt base base-devel
genfstab -p /mnt >> /mnt/etc/fstab
echo "$hostname" >/mnt/etc/hostname

# Copy setup file and execute
wget https://raw.github.com/Prince86EKNJ/royal-neko/master/os/arch/setup -O /mnt/root/setup
chmod +x /mnt/root/setup
arch-chroot /mnt /bin/bash /root/setup

# Clean up setup file
rm /mnt/root/setup

echo "Done!"
