#!/bin/bash
mkdir -p ~/aur
cd ~/aur
wget https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xf package-query.tar.gz 
tar -xf yaourt.tar.gz
cd package-query
makepkg -s --noconfirm
sudo pacman --noconfirm -U package-query*.pkg.tar.xz
cd ../yaourt
makepkg -s --noconfirm
sudo pacman --noconfirm -U yaourt*.pkg.tar.xz
