#!/bin/bash
lsblk
read -p "Enter parition device: " part
read -p "Enter hostname: " hostname

mount "$part" /mnt

# Install base
pacstrap /mnt base base-devel
genfstab -p /mnt >> /mnt/etc/fstab
echo "$hostname" >/mnt/etc/hostname

# Copy setup file and execute
curl https://raw.github.com/Prince86EKNJ/royal-neko/master/os/arch/setup > /mnt/root/setup
chmod +x /mnt/root/setup
arch-chroot /mnt /bin/bash /root/setup

# Clean up setup file
rm /mnt/root/setup

echo "Done!"
